### ISSUE TITLE
Introduced macOS Catalina (10.15) support

### ISSUE THREAD

**Issue by tib** [malcommac/UAParserSwift#4]
Hi,

first of all this library is amazing, congrats. 👍 

I have a quick question about the upcoming version:
    Is it possible to lower dependency so the lib could work with `.macOS(.v10_15)` as well?

Thanks.

Best,
Tib

**Comment by tib** [comment]
@malcommac I just created a PR for this issue, if you don't mind the change please be kind and merge. 

Thank you. 😄

**Comment by malcommac** [comment]
merged and available since 1.2.1. thank you
